// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PaluMacil/dan2/ent/amazonlist"
	"github.com/PaluMacil/dan2/ent/amazonorder"
	"github.com/PaluMacil/dan2/ent/amazonshare"
	"github.com/PaluMacil/dan2/ent/predicate"
	"github.com/PaluMacil/dan2/ent/user"
)

// AmazonListQuery is the builder for querying AmazonList entities.
type AmazonListQuery struct {
	config
	ctx              *QueryContext
	order            []amazonlist.OrderOption
	inters           []Interceptor
	predicates       []predicate.AmazonList
	withAmazonOrders *AmazonOrderQuery
	withOwner        *UserQuery
	withAmazonShares *AmazonShareQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AmazonListQuery builder.
func (alq *AmazonListQuery) Where(ps ...predicate.AmazonList) *AmazonListQuery {
	alq.predicates = append(alq.predicates, ps...)
	return alq
}

// Limit the number of records to be returned by this query.
func (alq *AmazonListQuery) Limit(limit int) *AmazonListQuery {
	alq.ctx.Limit = &limit
	return alq
}

// Offset to start from.
func (alq *AmazonListQuery) Offset(offset int) *AmazonListQuery {
	alq.ctx.Offset = &offset
	return alq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (alq *AmazonListQuery) Unique(unique bool) *AmazonListQuery {
	alq.ctx.Unique = &unique
	return alq
}

// Order specifies how the records should be ordered.
func (alq *AmazonListQuery) Order(o ...amazonlist.OrderOption) *AmazonListQuery {
	alq.order = append(alq.order, o...)
	return alq
}

// QueryAmazonOrders chains the current query on the "amazon_orders" edge.
func (alq *AmazonListQuery) QueryAmazonOrders() *AmazonOrderQuery {
	query := (&AmazonOrderClient{config: alq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := alq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := alq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(amazonlist.Table, amazonlist.FieldID, selector),
			sqlgraph.To(amazonorder.Table, amazonorder.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, amazonlist.AmazonOrdersTable, amazonlist.AmazonOrdersColumn),
		)
		fromU = sqlgraph.SetNeighbors(alq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOwner chains the current query on the "owner" edge.
func (alq *AmazonListQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: alq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := alq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := alq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(amazonlist.Table, amazonlist.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, amazonlist.OwnerTable, amazonlist.OwnerPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(alq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAmazonShares chains the current query on the "amazon_shares" edge.
func (alq *AmazonListQuery) QueryAmazonShares() *AmazonShareQuery {
	query := (&AmazonShareClient{config: alq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := alq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := alq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(amazonlist.Table, amazonlist.FieldID, selector),
			sqlgraph.To(amazonshare.Table, amazonshare.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, amazonlist.AmazonSharesTable, amazonlist.AmazonSharesColumn),
		)
		fromU = sqlgraph.SetNeighbors(alq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AmazonList entity from the query.
// Returns a *NotFoundError when no AmazonList was found.
func (alq *AmazonListQuery) First(ctx context.Context) (*AmazonList, error) {
	nodes, err := alq.Limit(1).All(setContextOp(ctx, alq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{amazonlist.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (alq *AmazonListQuery) FirstX(ctx context.Context) *AmazonList {
	node, err := alq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AmazonList ID from the query.
// Returns a *NotFoundError when no AmazonList ID was found.
func (alq *AmazonListQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = alq.Limit(1).IDs(setContextOp(ctx, alq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{amazonlist.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (alq *AmazonListQuery) FirstIDX(ctx context.Context) int {
	id, err := alq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AmazonList entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AmazonList entity is found.
// Returns a *NotFoundError when no AmazonList entities are found.
func (alq *AmazonListQuery) Only(ctx context.Context) (*AmazonList, error) {
	nodes, err := alq.Limit(2).All(setContextOp(ctx, alq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{amazonlist.Label}
	default:
		return nil, &NotSingularError{amazonlist.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (alq *AmazonListQuery) OnlyX(ctx context.Context) *AmazonList {
	node, err := alq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AmazonList ID in the query.
// Returns a *NotSingularError when more than one AmazonList ID is found.
// Returns a *NotFoundError when no entities are found.
func (alq *AmazonListQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = alq.Limit(2).IDs(setContextOp(ctx, alq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{amazonlist.Label}
	default:
		err = &NotSingularError{amazonlist.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (alq *AmazonListQuery) OnlyIDX(ctx context.Context) int {
	id, err := alq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AmazonLists.
func (alq *AmazonListQuery) All(ctx context.Context) ([]*AmazonList, error) {
	ctx = setContextOp(ctx, alq.ctx, "All")
	if err := alq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AmazonList, *AmazonListQuery]()
	return withInterceptors[[]*AmazonList](ctx, alq, qr, alq.inters)
}

// AllX is like All, but panics if an error occurs.
func (alq *AmazonListQuery) AllX(ctx context.Context) []*AmazonList {
	nodes, err := alq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AmazonList IDs.
func (alq *AmazonListQuery) IDs(ctx context.Context) (ids []int, err error) {
	if alq.ctx.Unique == nil && alq.path != nil {
		alq.Unique(true)
	}
	ctx = setContextOp(ctx, alq.ctx, "IDs")
	if err = alq.Select(amazonlist.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (alq *AmazonListQuery) IDsX(ctx context.Context) []int {
	ids, err := alq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (alq *AmazonListQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, alq.ctx, "Count")
	if err := alq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, alq, querierCount[*AmazonListQuery](), alq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (alq *AmazonListQuery) CountX(ctx context.Context) int {
	count, err := alq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (alq *AmazonListQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, alq.ctx, "Exist")
	switch _, err := alq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (alq *AmazonListQuery) ExistX(ctx context.Context) bool {
	exist, err := alq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AmazonListQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (alq *AmazonListQuery) Clone() *AmazonListQuery {
	if alq == nil {
		return nil
	}
	return &AmazonListQuery{
		config:           alq.config,
		ctx:              alq.ctx.Clone(),
		order:            append([]amazonlist.OrderOption{}, alq.order...),
		inters:           append([]Interceptor{}, alq.inters...),
		predicates:       append([]predicate.AmazonList{}, alq.predicates...),
		withAmazonOrders: alq.withAmazonOrders.Clone(),
		withOwner:        alq.withOwner.Clone(),
		withAmazonShares: alq.withAmazonShares.Clone(),
		// clone intermediate query.
		sql:  alq.sql.Clone(),
		path: alq.path,
	}
}

// WithAmazonOrders tells the query-builder to eager-load the nodes that are connected to
// the "amazon_orders" edge. The optional arguments are used to configure the query builder of the edge.
func (alq *AmazonListQuery) WithAmazonOrders(opts ...func(*AmazonOrderQuery)) *AmazonListQuery {
	query := (&AmazonOrderClient{config: alq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	alq.withAmazonOrders = query
	return alq
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (alq *AmazonListQuery) WithOwner(opts ...func(*UserQuery)) *AmazonListQuery {
	query := (&UserClient{config: alq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	alq.withOwner = query
	return alq
}

// WithAmazonShares tells the query-builder to eager-load the nodes that are connected to
// the "amazon_shares" edge. The optional arguments are used to configure the query builder of the edge.
func (alq *AmazonListQuery) WithAmazonShares(opts ...func(*AmazonShareQuery)) *AmazonListQuery {
	query := (&AmazonShareClient{config: alq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	alq.withAmazonShares = query
	return alq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AmazonList.Query().
//		GroupBy(amazonlist.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (alq *AmazonListQuery) GroupBy(field string, fields ...string) *AmazonListGroupBy {
	alq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AmazonListGroupBy{build: alq}
	grbuild.flds = &alq.ctx.Fields
	grbuild.label = amazonlist.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.AmazonList.Query().
//		Select(amazonlist.FieldCreatedAt).
//		Scan(ctx, &v)
func (alq *AmazonListQuery) Select(fields ...string) *AmazonListSelect {
	alq.ctx.Fields = append(alq.ctx.Fields, fields...)
	sbuild := &AmazonListSelect{AmazonListQuery: alq}
	sbuild.label = amazonlist.Label
	sbuild.flds, sbuild.scan = &alq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AmazonListSelect configured with the given aggregations.
func (alq *AmazonListQuery) Aggregate(fns ...AggregateFunc) *AmazonListSelect {
	return alq.Select().Aggregate(fns...)
}

func (alq *AmazonListQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range alq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, alq); err != nil {
				return err
			}
		}
	}
	for _, f := range alq.ctx.Fields {
		if !amazonlist.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if alq.path != nil {
		prev, err := alq.path(ctx)
		if err != nil {
			return err
		}
		alq.sql = prev
	}
	return nil
}

func (alq *AmazonListQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AmazonList, error) {
	var (
		nodes       = []*AmazonList{}
		_spec       = alq.querySpec()
		loadedTypes = [3]bool{
			alq.withAmazonOrders != nil,
			alq.withOwner != nil,
			alq.withAmazonShares != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AmazonList).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AmazonList{config: alq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, alq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := alq.withAmazonOrders; query != nil {
		if err := alq.loadAmazonOrders(ctx, query, nodes,
			func(n *AmazonList) { n.Edges.AmazonOrders = []*AmazonOrder{} },
			func(n *AmazonList, e *AmazonOrder) { n.Edges.AmazonOrders = append(n.Edges.AmazonOrders, e) }); err != nil {
			return nil, err
		}
	}
	if query := alq.withOwner; query != nil {
		if err := alq.loadOwner(ctx, query, nodes,
			func(n *AmazonList) { n.Edges.Owner = []*User{} },
			func(n *AmazonList, e *User) { n.Edges.Owner = append(n.Edges.Owner, e) }); err != nil {
			return nil, err
		}
	}
	if query := alq.withAmazonShares; query != nil {
		if err := alq.loadAmazonShares(ctx, query, nodes,
			func(n *AmazonList) { n.Edges.AmazonShares = []*AmazonShare{} },
			func(n *AmazonList, e *AmazonShare) { n.Edges.AmazonShares = append(n.Edges.AmazonShares, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (alq *AmazonListQuery) loadAmazonOrders(ctx context.Context, query *AmazonOrderQuery, nodes []*AmazonList, init func(*AmazonList), assign func(*AmazonList, *AmazonOrder)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*AmazonList)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.AmazonOrder(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(amazonlist.AmazonOrdersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.amazon_list_amazon_orders
		if fk == nil {
			return fmt.Errorf(`foreign-key "amazon_list_amazon_orders" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "amazon_list_amazon_orders" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (alq *AmazonListQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*AmazonList, init func(*AmazonList), assign func(*AmazonList, *User)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*AmazonList)
	nids := make(map[int]map[*AmazonList]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(amazonlist.OwnerTable)
		s.Join(joinT).On(s.C(user.FieldID), joinT.C(amazonlist.OwnerPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(amazonlist.OwnerPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(amazonlist.OwnerPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*AmazonList]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*User](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "owner" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (alq *AmazonListQuery) loadAmazonShares(ctx context.Context, query *AmazonShareQuery, nodes []*AmazonList, init func(*AmazonList), assign func(*AmazonList, *AmazonShare)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*AmazonList)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.AmazonShare(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(amazonlist.AmazonSharesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.amazon_list_amazon_shares
		if fk == nil {
			return fmt.Errorf(`foreign-key "amazon_list_amazon_shares" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "amazon_list_amazon_shares" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (alq *AmazonListQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := alq.querySpec()
	_spec.Node.Columns = alq.ctx.Fields
	if len(alq.ctx.Fields) > 0 {
		_spec.Unique = alq.ctx.Unique != nil && *alq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, alq.driver, _spec)
}

func (alq *AmazonListQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(amazonlist.Table, amazonlist.Columns, sqlgraph.NewFieldSpec(amazonlist.FieldID, field.TypeInt))
	_spec.From = alq.sql
	if unique := alq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if alq.path != nil {
		_spec.Unique = true
	}
	if fields := alq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, amazonlist.FieldID)
		for i := range fields {
			if fields[i] != amazonlist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := alq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := alq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := alq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := alq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (alq *AmazonListQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(alq.driver.Dialect())
	t1 := builder.Table(amazonlist.Table)
	columns := alq.ctx.Fields
	if len(columns) == 0 {
		columns = amazonlist.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if alq.sql != nil {
		selector = alq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if alq.ctx.Unique != nil && *alq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range alq.predicates {
		p(selector)
	}
	for _, p := range alq.order {
		p(selector)
	}
	if offset := alq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := alq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AmazonListGroupBy is the group-by builder for AmazonList entities.
type AmazonListGroupBy struct {
	selector
	build *AmazonListQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (algb *AmazonListGroupBy) Aggregate(fns ...AggregateFunc) *AmazonListGroupBy {
	algb.fns = append(algb.fns, fns...)
	return algb
}

// Scan applies the selector query and scans the result into the given value.
func (algb *AmazonListGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, algb.build.ctx, "GroupBy")
	if err := algb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AmazonListQuery, *AmazonListGroupBy](ctx, algb.build, algb, algb.build.inters, v)
}

func (algb *AmazonListGroupBy) sqlScan(ctx context.Context, root *AmazonListQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(algb.fns))
	for _, fn := range algb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*algb.flds)+len(algb.fns))
		for _, f := range *algb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*algb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := algb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AmazonListSelect is the builder for selecting fields of AmazonList entities.
type AmazonListSelect struct {
	*AmazonListQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (als *AmazonListSelect) Aggregate(fns ...AggregateFunc) *AmazonListSelect {
	als.fns = append(als.fns, fns...)
	return als
}

// Scan applies the selector query and scans the result into the given value.
func (als *AmazonListSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, als.ctx, "Select")
	if err := als.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AmazonListQuery, *AmazonListSelect](ctx, als.AmazonListQuery, als, als.inters, v)
}

func (als *AmazonListSelect) sqlScan(ctx context.Context, root *AmazonListQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(als.fns))
	for _, fn := range als.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*als.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := als.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
