// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PaluMacil/dan2/ent/movielist"
	"github.com/PaluMacil/dan2/ent/movielistshare"
	"github.com/PaluMacil/dan2/ent/predicate"
	"github.com/PaluMacil/dan2/ent/user"
)

// MovieListShareQuery is the builder for querying MovieListShare entities.
type MovieListShareQuery struct {
	config
	ctx           *QueryContext
	order         []movielistshare.OrderOption
	inters        []Interceptor
	predicates    []predicate.MovieListShare
	withUser      *UserQuery
	withMovieList *MovieListQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MovieListShareQuery builder.
func (mlsq *MovieListShareQuery) Where(ps ...predicate.MovieListShare) *MovieListShareQuery {
	mlsq.predicates = append(mlsq.predicates, ps...)
	return mlsq
}

// Limit the number of records to be returned by this query.
func (mlsq *MovieListShareQuery) Limit(limit int) *MovieListShareQuery {
	mlsq.ctx.Limit = &limit
	return mlsq
}

// Offset to start from.
func (mlsq *MovieListShareQuery) Offset(offset int) *MovieListShareQuery {
	mlsq.ctx.Offset = &offset
	return mlsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mlsq *MovieListShareQuery) Unique(unique bool) *MovieListShareQuery {
	mlsq.ctx.Unique = &unique
	return mlsq
}

// Order specifies how the records should be ordered.
func (mlsq *MovieListShareQuery) Order(o ...movielistshare.OrderOption) *MovieListShareQuery {
	mlsq.order = append(mlsq.order, o...)
	return mlsq
}

// QueryUser chains the current query on the "user" edge.
func (mlsq *MovieListShareQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: mlsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mlsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mlsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(movielistshare.Table, movielistshare.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, movielistshare.UserTable, movielistshare.UserPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(mlsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMovieList chains the current query on the "movie_list" edge.
func (mlsq *MovieListShareQuery) QueryMovieList() *MovieListQuery {
	query := (&MovieListClient{config: mlsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mlsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mlsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(movielistshare.Table, movielistshare.FieldID, selector),
			sqlgraph.To(movielist.Table, movielist.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, movielistshare.MovieListTable, movielistshare.MovieListPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(mlsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MovieListShare entity from the query.
// Returns a *NotFoundError when no MovieListShare was found.
func (mlsq *MovieListShareQuery) First(ctx context.Context) (*MovieListShare, error) {
	nodes, err := mlsq.Limit(1).All(setContextOp(ctx, mlsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{movielistshare.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mlsq *MovieListShareQuery) FirstX(ctx context.Context) *MovieListShare {
	node, err := mlsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MovieListShare ID from the query.
// Returns a *NotFoundError when no MovieListShare ID was found.
func (mlsq *MovieListShareQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mlsq.Limit(1).IDs(setContextOp(ctx, mlsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{movielistshare.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mlsq *MovieListShareQuery) FirstIDX(ctx context.Context) int {
	id, err := mlsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MovieListShare entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MovieListShare entity is found.
// Returns a *NotFoundError when no MovieListShare entities are found.
func (mlsq *MovieListShareQuery) Only(ctx context.Context) (*MovieListShare, error) {
	nodes, err := mlsq.Limit(2).All(setContextOp(ctx, mlsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{movielistshare.Label}
	default:
		return nil, &NotSingularError{movielistshare.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mlsq *MovieListShareQuery) OnlyX(ctx context.Context) *MovieListShare {
	node, err := mlsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MovieListShare ID in the query.
// Returns a *NotSingularError when more than one MovieListShare ID is found.
// Returns a *NotFoundError when no entities are found.
func (mlsq *MovieListShareQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mlsq.Limit(2).IDs(setContextOp(ctx, mlsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{movielistshare.Label}
	default:
		err = &NotSingularError{movielistshare.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mlsq *MovieListShareQuery) OnlyIDX(ctx context.Context) int {
	id, err := mlsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MovieListShares.
func (mlsq *MovieListShareQuery) All(ctx context.Context) ([]*MovieListShare, error) {
	ctx = setContextOp(ctx, mlsq.ctx, "All")
	if err := mlsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MovieListShare, *MovieListShareQuery]()
	return withInterceptors[[]*MovieListShare](ctx, mlsq, qr, mlsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mlsq *MovieListShareQuery) AllX(ctx context.Context) []*MovieListShare {
	nodes, err := mlsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MovieListShare IDs.
func (mlsq *MovieListShareQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mlsq.ctx.Unique == nil && mlsq.path != nil {
		mlsq.Unique(true)
	}
	ctx = setContextOp(ctx, mlsq.ctx, "IDs")
	if err = mlsq.Select(movielistshare.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mlsq *MovieListShareQuery) IDsX(ctx context.Context) []int {
	ids, err := mlsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mlsq *MovieListShareQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mlsq.ctx, "Count")
	if err := mlsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mlsq, querierCount[*MovieListShareQuery](), mlsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mlsq *MovieListShareQuery) CountX(ctx context.Context) int {
	count, err := mlsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mlsq *MovieListShareQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mlsq.ctx, "Exist")
	switch _, err := mlsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mlsq *MovieListShareQuery) ExistX(ctx context.Context) bool {
	exist, err := mlsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MovieListShareQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mlsq *MovieListShareQuery) Clone() *MovieListShareQuery {
	if mlsq == nil {
		return nil
	}
	return &MovieListShareQuery{
		config:        mlsq.config,
		ctx:           mlsq.ctx.Clone(),
		order:         append([]movielistshare.OrderOption{}, mlsq.order...),
		inters:        append([]Interceptor{}, mlsq.inters...),
		predicates:    append([]predicate.MovieListShare{}, mlsq.predicates...),
		withUser:      mlsq.withUser.Clone(),
		withMovieList: mlsq.withMovieList.Clone(),
		// clone intermediate query.
		sql:  mlsq.sql.Clone(),
		path: mlsq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (mlsq *MovieListShareQuery) WithUser(opts ...func(*UserQuery)) *MovieListShareQuery {
	query := (&UserClient{config: mlsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mlsq.withUser = query
	return mlsq
}

// WithMovieList tells the query-builder to eager-load the nodes that are connected to
// the "movie_list" edge. The optional arguments are used to configure the query builder of the edge.
func (mlsq *MovieListShareQuery) WithMovieList(opts ...func(*MovieListQuery)) *MovieListShareQuery {
	query := (&MovieListClient{config: mlsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mlsq.withMovieList = query
	return mlsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CanEdit bool `json:"can_edit,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MovieListShare.Query().
//		GroupBy(movielistshare.FieldCanEdit).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mlsq *MovieListShareQuery) GroupBy(field string, fields ...string) *MovieListShareGroupBy {
	mlsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MovieListShareGroupBy{build: mlsq}
	grbuild.flds = &mlsq.ctx.Fields
	grbuild.label = movielistshare.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CanEdit bool `json:"can_edit,omitempty"`
//	}
//
//	client.MovieListShare.Query().
//		Select(movielistshare.FieldCanEdit).
//		Scan(ctx, &v)
func (mlsq *MovieListShareQuery) Select(fields ...string) *MovieListShareSelect {
	mlsq.ctx.Fields = append(mlsq.ctx.Fields, fields...)
	sbuild := &MovieListShareSelect{MovieListShareQuery: mlsq}
	sbuild.label = movielistshare.Label
	sbuild.flds, sbuild.scan = &mlsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MovieListShareSelect configured with the given aggregations.
func (mlsq *MovieListShareQuery) Aggregate(fns ...AggregateFunc) *MovieListShareSelect {
	return mlsq.Select().Aggregate(fns...)
}

func (mlsq *MovieListShareQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mlsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mlsq); err != nil {
				return err
			}
		}
	}
	for _, f := range mlsq.ctx.Fields {
		if !movielistshare.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mlsq.path != nil {
		prev, err := mlsq.path(ctx)
		if err != nil {
			return err
		}
		mlsq.sql = prev
	}
	return nil
}

func (mlsq *MovieListShareQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MovieListShare, error) {
	var (
		nodes       = []*MovieListShare{}
		_spec       = mlsq.querySpec()
		loadedTypes = [2]bool{
			mlsq.withUser != nil,
			mlsq.withMovieList != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MovieListShare).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MovieListShare{config: mlsq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mlsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mlsq.withUser; query != nil {
		if err := mlsq.loadUser(ctx, query, nodes,
			func(n *MovieListShare) { n.Edges.User = []*User{} },
			func(n *MovieListShare, e *User) { n.Edges.User = append(n.Edges.User, e) }); err != nil {
			return nil, err
		}
	}
	if query := mlsq.withMovieList; query != nil {
		if err := mlsq.loadMovieList(ctx, query, nodes,
			func(n *MovieListShare) { n.Edges.MovieList = []*MovieList{} },
			func(n *MovieListShare, e *MovieList) { n.Edges.MovieList = append(n.Edges.MovieList, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mlsq *MovieListShareQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*MovieListShare, init func(*MovieListShare), assign func(*MovieListShare, *User)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*MovieListShare)
	nids := make(map[int]map[*MovieListShare]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(movielistshare.UserTable)
		s.Join(joinT).On(s.C(user.FieldID), joinT.C(movielistshare.UserPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(movielistshare.UserPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(movielistshare.UserPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*MovieListShare]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*User](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "user" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (mlsq *MovieListShareQuery) loadMovieList(ctx context.Context, query *MovieListQuery, nodes []*MovieListShare, init func(*MovieListShare), assign func(*MovieListShare, *MovieList)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*MovieListShare)
	nids := make(map[int]map[*MovieListShare]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(movielistshare.MovieListTable)
		s.Join(joinT).On(s.C(movielist.FieldID), joinT.C(movielistshare.MovieListPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(movielistshare.MovieListPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(movielistshare.MovieListPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*MovieListShare]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*MovieList](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "movie_list" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (mlsq *MovieListShareQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mlsq.querySpec()
	_spec.Node.Columns = mlsq.ctx.Fields
	if len(mlsq.ctx.Fields) > 0 {
		_spec.Unique = mlsq.ctx.Unique != nil && *mlsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mlsq.driver, _spec)
}

func (mlsq *MovieListShareQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(movielistshare.Table, movielistshare.Columns, sqlgraph.NewFieldSpec(movielistshare.FieldID, field.TypeInt))
	_spec.From = mlsq.sql
	if unique := mlsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mlsq.path != nil {
		_spec.Unique = true
	}
	if fields := mlsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, movielistshare.FieldID)
		for i := range fields {
			if fields[i] != movielistshare.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mlsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mlsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mlsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mlsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mlsq *MovieListShareQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mlsq.driver.Dialect())
	t1 := builder.Table(movielistshare.Table)
	columns := mlsq.ctx.Fields
	if len(columns) == 0 {
		columns = movielistshare.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mlsq.sql != nil {
		selector = mlsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mlsq.ctx.Unique != nil && *mlsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mlsq.predicates {
		p(selector)
	}
	for _, p := range mlsq.order {
		p(selector)
	}
	if offset := mlsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mlsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MovieListShareGroupBy is the group-by builder for MovieListShare entities.
type MovieListShareGroupBy struct {
	selector
	build *MovieListShareQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mlsgb *MovieListShareGroupBy) Aggregate(fns ...AggregateFunc) *MovieListShareGroupBy {
	mlsgb.fns = append(mlsgb.fns, fns...)
	return mlsgb
}

// Scan applies the selector query and scans the result into the given value.
func (mlsgb *MovieListShareGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mlsgb.build.ctx, "GroupBy")
	if err := mlsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MovieListShareQuery, *MovieListShareGroupBy](ctx, mlsgb.build, mlsgb, mlsgb.build.inters, v)
}

func (mlsgb *MovieListShareGroupBy) sqlScan(ctx context.Context, root *MovieListShareQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mlsgb.fns))
	for _, fn := range mlsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mlsgb.flds)+len(mlsgb.fns))
		for _, f := range *mlsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mlsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mlsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MovieListShareSelect is the builder for selecting fields of MovieListShare entities.
type MovieListShareSelect struct {
	*MovieListShareQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mlss *MovieListShareSelect) Aggregate(fns ...AggregateFunc) *MovieListShareSelect {
	mlss.fns = append(mlss.fns, fns...)
	return mlss
}

// Scan applies the selector query and scans the result into the given value.
func (mlss *MovieListShareSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mlss.ctx, "Select")
	if err := mlss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MovieListShareQuery, *MovieListShareSelect](ctx, mlss.MovieListShareQuery, mlss, mlss.inters, v)
}

func (mlss *MovieListShareSelect) sqlScan(ctx context.Context, root *MovieListShareQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mlss.fns))
	for _, fn := range mlss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mlss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mlss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
