// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/PaluMacil/dan2/ent/moviecollection"
	"github.com/PaluMacil/dan2/ent/moviecollectionshare"
	"github.com/PaluMacil/dan2/ent/user"
)

// MovieCollectionShare is the model entity for the MovieCollectionShare schema.
type MovieCollectionShare struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CanEdit holds the value of the "can_edit" field.
	CanEdit bool `json:"can_edit,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MovieCollectionShareQuery when eager-loading is set.
	Edges                                    MovieCollectionShareEdges `json:"edges"`
	movie_collection_movie_collection_shares *int
	user_movie_collection_shares             *int
	selectValues                             sql.SelectValues
}

// MovieCollectionShareEdges holds the relations/edges for other nodes in the graph.
type MovieCollectionShareEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// MovieCollection holds the value of the movie_collection edge.
	MovieCollection *MovieCollection `json:"movie_collection,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MovieCollectionShareEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// MovieCollectionOrErr returns the MovieCollection value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MovieCollectionShareEdges) MovieCollectionOrErr() (*MovieCollection, error) {
	if e.loadedTypes[1] {
		if e.MovieCollection == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: moviecollection.Label}
		}
		return e.MovieCollection, nil
	}
	return nil, &NotLoadedError{edge: "movie_collection"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MovieCollectionShare) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case moviecollectionshare.FieldCanEdit:
			values[i] = new(sql.NullBool)
		case moviecollectionshare.FieldID:
			values[i] = new(sql.NullInt64)
		case moviecollectionshare.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case moviecollectionshare.ForeignKeys[0]: // movie_collection_movie_collection_shares
			values[i] = new(sql.NullInt64)
		case moviecollectionshare.ForeignKeys[1]: // user_movie_collection_shares
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MovieCollectionShare fields.
func (mcs *MovieCollectionShare) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case moviecollectionshare.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			mcs.ID = int(value.Int64)
		case moviecollectionshare.FieldCanEdit:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field can_edit", values[i])
			} else if value.Valid {
				mcs.CanEdit = value.Bool
			}
		case moviecollectionshare.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				mcs.CreatedAt = value.Time
			}
		case moviecollectionshare.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field movie_collection_movie_collection_shares", value)
			} else if value.Valid {
				mcs.movie_collection_movie_collection_shares = new(int)
				*mcs.movie_collection_movie_collection_shares = int(value.Int64)
			}
		case moviecollectionshare.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_movie_collection_shares", value)
			} else if value.Valid {
				mcs.user_movie_collection_shares = new(int)
				*mcs.user_movie_collection_shares = int(value.Int64)
			}
		default:
			mcs.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MovieCollectionShare.
// This includes values selected through modifiers, order, etc.
func (mcs *MovieCollectionShare) Value(name string) (ent.Value, error) {
	return mcs.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the MovieCollectionShare entity.
func (mcs *MovieCollectionShare) QueryUser() *UserQuery {
	return NewMovieCollectionShareClient(mcs.config).QueryUser(mcs)
}

// QueryMovieCollection queries the "movie_collection" edge of the MovieCollectionShare entity.
func (mcs *MovieCollectionShare) QueryMovieCollection() *MovieCollectionQuery {
	return NewMovieCollectionShareClient(mcs.config).QueryMovieCollection(mcs)
}

// Update returns a builder for updating this MovieCollectionShare.
// Note that you need to call MovieCollectionShare.Unwrap() before calling this method if this MovieCollectionShare
// was returned from a transaction, and the transaction was committed or rolled back.
func (mcs *MovieCollectionShare) Update() *MovieCollectionShareUpdateOne {
	return NewMovieCollectionShareClient(mcs.config).UpdateOne(mcs)
}

// Unwrap unwraps the MovieCollectionShare entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (mcs *MovieCollectionShare) Unwrap() *MovieCollectionShare {
	_tx, ok := mcs.config.driver.(*txDriver)
	if !ok {
		panic("ent: MovieCollectionShare is not a transactional entity")
	}
	mcs.config.driver = _tx.drv
	return mcs
}

// String implements the fmt.Stringer.
func (mcs *MovieCollectionShare) String() string {
	var builder strings.Builder
	builder.WriteString("MovieCollectionShare(")
	builder.WriteString(fmt.Sprintf("id=%v, ", mcs.ID))
	builder.WriteString("can_edit=")
	builder.WriteString(fmt.Sprintf("%v", mcs.CanEdit))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(mcs.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MovieCollectionShares is a parsable slice of MovieCollectionShare.
type MovieCollectionShares []*MovieCollectionShare
