// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PaluMacil/dan2/ent/moviecollection"
	"github.com/PaluMacil/dan2/ent/predicate"
)

// MovieCollectionDelete is the builder for deleting a MovieCollection entity.
type MovieCollectionDelete struct {
	config
	hooks    []Hook
	mutation *MovieCollectionMutation
}

// Where appends a list predicates to the MovieCollectionDelete builder.
func (mcd *MovieCollectionDelete) Where(ps ...predicate.MovieCollection) *MovieCollectionDelete {
	mcd.mutation.Where(ps...)
	return mcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mcd *MovieCollectionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mcd.sqlExec, mcd.mutation, mcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mcd *MovieCollectionDelete) ExecX(ctx context.Context) int {
	n, err := mcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mcd *MovieCollectionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(moviecollection.Table, sqlgraph.NewFieldSpec(moviecollection.FieldID, field.TypeInt))
	if ps := mcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mcd.mutation.done = true
	return affected, err
}

// MovieCollectionDeleteOne is the builder for deleting a single MovieCollection entity.
type MovieCollectionDeleteOne struct {
	mcd *MovieCollectionDelete
}

// Where appends a list predicates to the MovieCollectionDelete builder.
func (mcdo *MovieCollectionDeleteOne) Where(ps ...predicate.MovieCollection) *MovieCollectionDeleteOne {
	mcdo.mcd.mutation.Where(ps...)
	return mcdo
}

// Exec executes the deletion query.
func (mcdo *MovieCollectionDeleteOne) Exec(ctx context.Context) error {
	n, err := mcdo.mcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{moviecollection.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mcdo *MovieCollectionDeleteOne) ExecX(ctx context.Context) {
	if err := mcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
