// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/PaluMacil/dan2/ent/amazonlist"
	"github.com/PaluMacil/dan2/ent/amazonorder"
	"github.com/PaluMacil/dan2/ent/amazonshare"
	"github.com/PaluMacil/dan2/ent/drink"
	"github.com/PaluMacil/dan2/ent/grocerylist"
	"github.com/PaluMacil/dan2/ent/grocerylistitem"
	"github.com/PaluMacil/dan2/ent/grocerylistshare"
	"github.com/PaluMacil/dan2/ent/movie"
	"github.com/PaluMacil/dan2/ent/movielist"
	"github.com/PaluMacil/dan2/ent/movielistshare"
	"github.com/PaluMacil/dan2/ent/schema"
	"github.com/PaluMacil/dan2/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	amazonlistFields := schema.AmazonList{}.Fields()
	_ = amazonlistFields
	// amazonlistDescCreatedAt is the schema descriptor for created_at field.
	amazonlistDescCreatedAt := amazonlistFields[0].Descriptor()
	// amazonlist.DefaultCreatedAt holds the default value on creation for the created_at field.
	amazonlist.DefaultCreatedAt = amazonlistDescCreatedAt.Default.(func() time.Time)
	amazonorderFields := schema.AmazonOrder{}.Fields()
	_ = amazonorderFields
	// amazonorderDescCreatedAt is the schema descriptor for created_at field.
	amazonorderDescCreatedAt := amazonorderFields[13].Descriptor()
	// amazonorder.DefaultCreatedAt holds the default value on creation for the created_at field.
	amazonorder.DefaultCreatedAt = amazonorderDescCreatedAt.Default.(func() time.Time)
	amazonshareFields := schema.AmazonShare{}.Fields()
	_ = amazonshareFields
	// amazonshareDescCanEdit is the schema descriptor for can_edit field.
	amazonshareDescCanEdit := amazonshareFields[0].Descriptor()
	// amazonshare.DefaultCanEdit holds the default value on creation for the can_edit field.
	amazonshare.DefaultCanEdit = amazonshareDescCanEdit.Default.(bool)
	drinkFields := schema.Drink{}.Fields()
	_ = drinkFields
	// drinkDescAbv is the schema descriptor for abv field.
	drinkDescAbv := drinkFields[1].Descriptor()
	// drink.DefaultAbv holds the default value on creation for the abv field.
	drink.DefaultAbv = drinkDescAbv.Default.(int8)
	// drinkDescOunces is the schema descriptor for ounces field.
	drinkDescOunces := drinkFields[2].Descriptor()
	// drink.DefaultOunces holds the default value on creation for the ounces field.
	drink.DefaultOunces = drinkDescOunces.Default.(int8)
	// drinkDescYear is the schema descriptor for year field.
	drinkDescYear := drinkFields[3].Descriptor()
	// drink.DefaultYear holds the default value on creation for the year field.
	drink.DefaultYear = drinkDescYear.Default.(func() int)
	// drinkDescMonth is the schema descriptor for month field.
	drinkDescMonth := drinkFields[4].Descriptor()
	// drink.DefaultMonth holds the default value on creation for the month field.
	drink.DefaultMonth = drinkDescMonth.Default.(func() int)
	// drinkDescDay is the schema descriptor for day field.
	drinkDescDay := drinkFields[5].Descriptor()
	// drink.DefaultDay holds the default value on creation for the day field.
	drink.DefaultDay = drinkDescDay.Default.(func() int)
	// drinkDescNote is the schema descriptor for note field.
	drinkDescNote := drinkFields[6].Descriptor()
	// drink.DefaultNote holds the default value on creation for the note field.
	drink.DefaultNote = drinkDescNote.Default.(string)
	// drinkDescCreatedAt is the schema descriptor for created_at field.
	drinkDescCreatedAt := drinkFields[7].Descriptor()
	// drink.DefaultCreatedAt holds the default value on creation for the created_at field.
	drink.DefaultCreatedAt = drinkDescCreatedAt.Default.(func() time.Time)
	grocerylistFields := schema.GroceryList{}.Fields()
	_ = grocerylistFields
	// grocerylistDescName is the schema descriptor for name field.
	grocerylistDescName := grocerylistFields[0].Descriptor()
	// grocerylist.DefaultName holds the default value on creation for the name field.
	grocerylist.DefaultName = grocerylistDescName.Default.(string)
	// grocerylistDescNote is the schema descriptor for note field.
	grocerylistDescNote := grocerylistFields[1].Descriptor()
	// grocerylist.DefaultNote holds the default value on creation for the note field.
	grocerylist.DefaultNote = grocerylistDescNote.Default.(string)
	// grocerylistDescArchived is the schema descriptor for archived field.
	grocerylistDescArchived := grocerylistFields[2].Descriptor()
	// grocerylist.DefaultArchived holds the default value on creation for the archived field.
	grocerylist.DefaultArchived = grocerylistDescArchived.Default.(bool)
	// grocerylistDescCreatedAt is the schema descriptor for created_at field.
	grocerylistDescCreatedAt := grocerylistFields[3].Descriptor()
	// grocerylist.DefaultCreatedAt holds the default value on creation for the created_at field.
	grocerylist.DefaultCreatedAt = grocerylistDescCreatedAt.Default.(func() time.Time)
	grocerylistitemFields := schema.GroceryListItem{}.Fields()
	_ = grocerylistitemFields
	// grocerylistitemDescQuantity is the schema descriptor for quantity field.
	grocerylistitemDescQuantity := grocerylistitemFields[1].Descriptor()
	// grocerylistitem.DefaultQuantity holds the default value on creation for the quantity field.
	grocerylistitem.DefaultQuantity = grocerylistitemDescQuantity.Default.(int)
	// grocerylistitemDescNote is the schema descriptor for note field.
	grocerylistitemDescNote := grocerylistitemFields[2].Descriptor()
	// grocerylistitem.DefaultNote holds the default value on creation for the note field.
	grocerylistitem.DefaultNote = grocerylistitemDescNote.Default.(string)
	// grocerylistitemDescCreatedAt is the schema descriptor for created_at field.
	grocerylistitemDescCreatedAt := grocerylistitemFields[3].Descriptor()
	// grocerylistitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	grocerylistitem.DefaultCreatedAt = grocerylistitemDescCreatedAt.Default.(func() time.Time)
	grocerylistshareFields := schema.GroceryListShare{}.Fields()
	_ = grocerylistshareFields
	// grocerylistshareDescCanEdit is the schema descriptor for can_edit field.
	grocerylistshareDescCanEdit := grocerylistshareFields[0].Descriptor()
	// grocerylistshare.DefaultCanEdit holds the default value on creation for the can_edit field.
	grocerylistshare.DefaultCanEdit = grocerylistshareDescCanEdit.Default.(bool)
	// grocerylistshareDescCreatedAt is the schema descriptor for created_at field.
	grocerylistshareDescCreatedAt := grocerylistshareFields[1].Descriptor()
	// grocerylistshare.DefaultCreatedAt holds the default value on creation for the created_at field.
	grocerylistshare.DefaultCreatedAt = grocerylistshareDescCreatedAt.Default.(func() time.Time)
	movieFields := schema.Movie{}.Fields()
	_ = movieFields
	// movieDescNote is the schema descriptor for note field.
	movieDescNote := movieFields[1].Descriptor()
	// movie.DefaultNote holds the default value on creation for the note field.
	movie.DefaultNote = movieDescNote.Default.(string)
	// movieDescWatched is the schema descriptor for watched field.
	movieDescWatched := movieFields[2].Descriptor()
	// movie.DefaultWatched holds the default value on creation for the watched field.
	movie.DefaultWatched = movieDescWatched.Default.(bool)
	// movieDescCreatedAt is the schema descriptor for created_at field.
	movieDescCreatedAt := movieFields[3].Descriptor()
	// movie.DefaultCreatedAt holds the default value on creation for the created_at field.
	movie.DefaultCreatedAt = movieDescCreatedAt.Default.(func() time.Time)
	movielistFields := schema.MovieList{}.Fields()
	_ = movielistFields
	// movielistDescName is the schema descriptor for name field.
	movielistDescName := movielistFields[0].Descriptor()
	// movielist.DefaultName holds the default value on creation for the name field.
	movielist.DefaultName = movielistDescName.Default.(string)
	// movielistDescNote is the schema descriptor for note field.
	movielistDescNote := movielistFields[1].Descriptor()
	// movielist.DefaultNote holds the default value on creation for the note field.
	movielist.DefaultNote = movielistDescNote.Default.(string)
	// movielistDescShowWatched is the schema descriptor for show_watched field.
	movielistDescShowWatched := movielistFields[2].Descriptor()
	// movielist.DefaultShowWatched holds the default value on creation for the show_watched field.
	movielist.DefaultShowWatched = movielistDescShowWatched.Default.(bool)
	// movielistDescCreatedAt is the schema descriptor for created_at field.
	movielistDescCreatedAt := movielistFields[3].Descriptor()
	// movielist.DefaultCreatedAt holds the default value on creation for the created_at field.
	movielist.DefaultCreatedAt = movielistDescCreatedAt.Default.(func() time.Time)
	movielistshareFields := schema.MovieListShare{}.Fields()
	_ = movielistshareFields
	// movielistshareDescCanEdit is the schema descriptor for can_edit field.
	movielistshareDescCanEdit := movielistshareFields[0].Descriptor()
	// movielistshare.DefaultCanEdit holds the default value on creation for the can_edit field.
	movielistshare.DefaultCanEdit = movielistshareDescCanEdit.Default.(bool)
	// movielistshareDescCreatedAt is the schema descriptor for created_at field.
	movielistshareDescCreatedAt := movielistshareFields[1].Descriptor()
	// movielistshare.DefaultCreatedAt holds the default value on creation for the created_at field.
	movielistshare.DefaultCreatedAt = movielistshareDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescNameChanges is the schema descriptor for name_changes field.
	userDescNameChanges := userFields[1].Descriptor()
	// user.DefaultNameChanges holds the default value on creation for the name_changes field.
	user.DefaultNameChanges = userDescNameChanges.Default.(int8)
	// userDescVerified is the schema descriptor for verified field.
	userDescVerified := userFields[3].Descriptor()
	// user.DefaultVerified holds the default value on creation for the verified field.
	user.DefaultVerified = userDescVerified.Default.(bool)
	// userDescLocked is the schema descriptor for locked field.
	userDescLocked := userFields[4].Descriptor()
	// user.DefaultLocked holds the default value on creation for the locked field.
	user.DefaultLocked = userDescLocked.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[6].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}
