// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AmazonList is the predicate function for amazonlist builders.
type AmazonList func(*sql.Selector)

// AmazonOrder is the predicate function for amazonorder builders.
type AmazonOrder func(*sql.Selector)

// AmazonShare is the predicate function for amazonshare builders.
type AmazonShare func(*sql.Selector)

// Drink is the predicate function for drink builders.
type Drink func(*sql.Selector)

// GroceryList is the predicate function for grocerylist builders.
type GroceryList func(*sql.Selector)

// GroceryListItem is the predicate function for grocerylistitem builders.
type GroceryListItem func(*sql.Selector)

// GroceryListShare is the predicate function for grocerylistshare builders.
type GroceryListShare func(*sql.Selector)

// Movie is the predicate function for movie builders.
type Movie func(*sql.Selector)

// MovieList is the predicate function for movielist builders.
type MovieList func(*sql.Selector)

// MovieListShare is the predicate function for movielistshare builders.
type MovieListShare func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
